### DISCUSSION TITLE
How can I remove the image thumbnail?

### DISCUSSION THREAD

**Discussion by Chong-long** [Nerixyz/current-song2#556] [Q&A]
Is there a way that I can remove the image-container and only keep the song info?

**Comment by Nerixyz** [comment]
You can add a custom theme that removes it:

```css
#image-container {
  display: none;
}
```
