### DISCUSSION TITLE
Adding the album title to the display?

### DISCUSSION THREAD

**Discussion by Ugyuu** [Nerixyz/current-song2#598] [Q&A] [answered]
Hello! Big css newbie here (was only taught the basics and it's been a long time since I got to use it, lol!).
Currently trying to figure out how to edit the theming and config so that it shows the album title in the display as well. What are all the things I need to change to make that happen?

I have this set up so far:
`[modules.file]`
`enabled = true`
`path = "current_song.txt"`
`format = "{artist} - {title} - {album-name?}"`

Tried it with or without a "?" but in the `current_song.txt` the album has an extra dash, but the rest is blank, even if there is an album title for the currently playing song. The display itself also doesn't show anything because of this.

For the theming I see you can do something like `#song-container.with-album` or add a CSS variable `--album`, but I can't wrap my head around _how_ to formulate it.
For example, I tried something like this:
`#song-container.with-image::before {`
` content: var(--album);`
`}`
Maybe I'm stupid and clearly forgetting about something?

For reference, using local music files, some with or without Album titles filled in, playing in foobar2000.

**Comment by Nerixyz** [comment]
> Tried it with or without a "?" but in the `current_song.txt` the album has an extra dash, but the rest is blank, even if there is an album title for the currently playing song. The display itself also doesn't show anything because of this.

So the album name never shows for you?
At least when using Spotify, this works for me.

One thing that's a bit annoying is that you can't express "don't print the dash if the album name is empty". I opened https://github.com/Nerixyz/current-song2/issues/599 for this.

> For the theming I see you can do something like `#song-container.with-album` or add a CSS variable `--album`, but I can't wrap my head around _how_ to formulate it.

I think my answer [here](https://github.com/Nerixyz/current-song2/issues/523#issuecomment-2466847606) should be what you want:

```css
/* Make the container a bit bigger as it contains three lines now */
#song-container.with-image.with-album {
  --max-height: 5.5em;
  --height: 5.5em;
}
#song-container.with-album #mq-subtitle::after {
  content: var(--album);
  font-size: 0.8em;
}
```
![](https://github.com/user-attachments/assets/727b5d54-95a6-411d-804b-e2eaa8f8791e)

**Reply by Lordmau5** [reply]
I remember seeing that answer in another discussion already and was wondering why there's no proper native way of showing a 3rd line for the album title without the CSS tricks?

Reason why I'm asking is because I'm using `-webkit-text-stroke` in combination with `paint-order: stroke fill;` so it will first do the outline and then the text (basically a native way in CSS to have outlines on the *outside* instead of on the *inside* nowadays)

However, that doesn't work for CSS content... (It just does an inside outline again)
![image](https://github.com/user-attachments/assets/015b9e3b-2899-4090-9a94-f84f3d7da456)

Also, the album title sadly doesn't scroll this way either...
![image](https://github.com/user-attachments/assets/0fc7e0f3-552f-496c-a326-93177ff989c4)

Would it perhaps be possible to add a native 3rd line with the album title in a dedicated HTML element that's stylable through the use of, say, a query parameter like `&show_album` or similar? Would be really cool :)

The CSS I use for the proper outline (and shadow)
```css
#title, #subtitle {
	-webkit-text-stroke: black 3px;
	paint-order: stroke fill;
	text-shadow: black 0 2px 10px;
}
```
