### ISSUE TITLE
Transparent Background Still Mildly Visible

### ISSUE THREAD

**Issue by BEEF-Gaming** [Nerixyz/current-song2#387]
Heyyo, first off, THANK YOU. This little program is amazing, and it just works. No gimmicks, constant refreshing, it's great!

The one and only thing I've noticed is when the background is set to transparent, there's still a little bubble visible. 

Would it be possible to remove this?

![image](https://github.com/Nerixyz/current-song2/assets/95342710/855becfb-3fc6-4e29-8c47-831ad305da5f)

**Comment by Nerixyz** [comment]
Thank you for opening this issue! I didn't update the example when adding a shadow to the container. The following should fix it:

```css
:root {
    --text-shadow-color: #0007;
}

#song-container {
    background: transparent;
    transition: none;
    overflow: visible;
    box-shadow: none; /*  <-- this line */
}

#song-info :is(h1, h2) {
    text-shadow: 1px 4px 15px var(--text-shadow-color, #0007);
}
```
