### ISSUE TITLE
min-width causes album art element to stretch

### ISSUE THREAD

**Issue by admiralflapjack** [Nerixyz/current-song2#404]
using this theme.css:
`:root {
    --theme-color: white;
    --image-overlay-opacity: 75%;
}
#song-container {
	min-width: 450px;
}`

results in the album art element being stretched (not the art itself) instead of adding whitespace on the right:

![image](https://github.com/Nerixyz/current-song2/assets/36775501/2c889be6-fabf-4650-b1e0-b48222c0d1fb)

**Comment by Nerixyz** [comment]
`#image-container` has `flex: 1 1` (`flex-grow: 1; flex-shrink: 1`). If you disable that, it works:

```css
:root {
  --theme-color: white;
  --image-overlay-opacity: 75%;
}
#song-container {
  min-width: 450px;
}
#image-container {
  flex-grow: 0; /* disables growth of this element */
}
```
