### ISSUE TITLE
Output to file

### ISSUE THREAD

**Issue by Nerixyz** [Nerixyz/current-song2#69]
Config:

```toml
[file-output]
path = "path/to/file.txt"
type = "text"
# optional
format = "{artist} - {title}"
# or
type = "json"
```

* [ ] Output to text file
* [ ] Output to json
